services:
  hop-web:
    image: tomcat:10-jdk21
    platform: linux/amd64
    container_name: hop-web-dev
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      HOP_LOG_LEVEL: Debug
      HOP_AUDIT_FOLDER: /opt/hop/audit
      HOP_CONFIG_FOLDER: /opt/hop/config
      HOP_PLUGIN_BASE_FOLDERS: /opt/hop/plugins
      HOP_PASSWORD_ENCODER_PLUGIN: Hop
      HOP_OPTIONS: -Dorg.eclipse.rap.rwt.resourceLocation=/tmp/rwt-resources -Dswt.use.gtk3=false -Duser.timezone=Asia/Shanghai
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dorg.eclipse.rap.rwt.resourceLocation=/tmp/rwt-resources -DHOP_AUDIT_FOLDER=/opt/hop/audit -DHOP_CONFIG_FOLDER=/opt/hop/config -DHOP_LOG_LEVEL=Debug -DHOP_PASSWORD_ENCODER_PLUGIN=Hop -DHOP_PLUGIN_BASE_FOLDERS=/opt/hop/plugins -Dswt.use.gtk3=false -Duser.timezone=Asia/Shanghai
    volumes:
      - ./assemblies/web/target/webapp:/usr/local/tomcat/webapps/ROOT
      - ./assemblies/web/target/webapp/config:/opt/hop/config
      - ./assemblies/client/target/hop/plugins:/opt/hop/plugins
      - ./assemblies/core/target/hop/lib/core:/tmp/hop-lib-core
    working_dir: /usr/local/tomcat
    command: >
      bash -c "
        cp -r /tmp/hop-lib-core/* webapps/ROOT/WEB-INF/lib/ &&
        mkdir -p /opt/hop/audit &&
        catalina.sh run
      "
