/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.rest.v1.resources.docs;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Service that loads and queries the URL-to-documentation mapping table. The mapping table is
 * generated by {@code scripts/build-url-mapping.py} and stored as {@code
 * docs/hop-assistant-manual/url-mapping.json}.
 */
public class UrlMappingService {

  private static final Logger LOG = LoggerFactory.getLogger(UrlMappingService.class);
  private static final UrlMappingService INSTANCE = new UrlMappingService();

  private volatile List<UrlMapping> mappings = Collections.emptyList();
  private volatile Map<String, UrlMapping> urlIndex = new ConcurrentHashMap<>();
  private volatile Map<String, UrlMapping> mdPathIndex = new ConcurrentHashMap<>();
  private volatile Map<String, UrlMapping> fileNameIndex = new ConcurrentHashMap<>();
  private volatile boolean loaded = false;

  public static UrlMappingService getInstance() {
    return INSTANCE;
  }

  private UrlMappingService() {}

  /** Loads the mapping table from the classpath or filesystem. */
  public synchronized void load() {
    if (loaded) {
      return;
    }
    try {
      ObjectMapper mapper = new ObjectMapper();
      InputStream is = loadMappingStream();
      if (is == null) {
        LOG.warn("url-mapping.json not found on classpath or filesystem");
        loaded = true;
        return;
      }
      UrlMappingRoot root = mapper.readValue(is, new TypeReference<UrlMappingRoot>() {});
      this.mappings = root.getMappings() != null ? root.getMappings() : Collections.emptyList();
      this.urlIndex = new ConcurrentHashMap<>();
      this.mdPathIndex = new ConcurrentHashMap<>();
      this.fileNameIndex = new ConcurrentHashMap<>();
      for (UrlMapping m : this.mappings) {
        if (m.getDocumentationUrl() != null) {
          urlIndex.put(m.getDocumentationUrl(), m);
        }
        if (m.getMdRelativePath() != null) {
          mdPathIndex.put(m.getMdRelativePath(), m);
          String fileName = java.nio.file.Path.of(m.getMdRelativePath()).getFileName().toString();
          fileNameIndex.put(fileName, m);
        }
      }
      scanAllMdFiles();
      loaded = true;
      Map<String, Object> stats = root.getStats();
      LOG.info(
          "Loaded URL mapping: {} total, {} matched, {} unmatched",
          stats.getOrDefault("total", 0),
          stats.getOrDefault("matched", 0),
          stats.getOrDefault("unmatched", 0));
    } catch (IOException e) {
      LOG.error("Failed to load url-mapping.json", e);
      loaded = true;
    }
  }

  private InputStream loadMappingStream() {
    InputStream is = getClass().getResourceAsStream("/org/apache/hop/rest/docs/url-mapping.json");
    if (is != null) {
      return is;
    }
    is = getClass().getResourceAsStream("/url-mapping.json");
    if (is != null) {
      return is;
    }
    String docsBase = System.getProperty("hop.docs.base", "docs/hop-assistant-manual");
    Path path = Path.of(docsBase, "url-mapping.json");
    if (Files.exists(path)) {
      try {
        return Files.newInputStream(path);
      } catch (IOException e) {
        LOG.warn("Failed to read mapping from filesystem: {}", path, e);
      }
    }
    return null;
  }

  /**
   * Looks up a documentation URL in the mapping table.
   *
   * @param docUrl the documentation URL path (e.g., "/pipeline/transforms/csvinput.html")
   * @return the mapping entry, or null if not found
   */
  public UrlMapping lookup(String docUrl) {
    load();
    if (docUrl == null || docUrl.isBlank()) {
      return null;
    }
    String normalized = docUrl.startsWith("/") ? docUrl : "/" + docUrl;
    return urlIndex.get(normalized);
  }

  /** Returns all mappings. */
  public List<UrlMapping> getAllMappings() {
    load();
    return mappings;
  }

  /**
   * Looks up a documentation URL by markdown relative path.
   *
   * @param mdRelativePath the markdown file relative path (e.g., "03-转换插件/流程控制类/abort.md")
   * @return the mapping entry, or null if not found
   */
  public UrlMapping lookupByMdPath(String mdRelativePath) {
    load();
    if (mdRelativePath == null || mdRelativePath.isBlank()) {
      return null;
    }
    return mdPathIndex.get(mdRelativePath);
  }

  /**
   * Looks up a documentation URL by markdown file name.
   *
   * @param fileName the markdown file name (e.g., "abort.md")
   * @return the mapping entry, or null if not found
   */
  public UrlMapping lookupByFileName(String fileName) {
    load();
    if (fileName == null || fileName.isBlank()) {
      return null;
    }
    return fileNameIndex.get(fileName);
  }

  /** Returns mapping statistics. */
  public Map<String, Object> getStats() {
    load();
    if (!mappings.isEmpty()) {
      long matched = mappings.stream().filter(m -> "matched".equals(m.getStatus())).count();
      long unmatched = mappings.size() - matched;
      return Map.of(
          "total",
          (long) mappings.size(),
          "matched",
          matched,
          "unmatched",
          unmatched,
          "matchRate",
          String.format("%.1f%%", matched * 100.0 / mappings.size()));
    }
    return Map.of("total", 0, "matched", 0, "unmatched", 0, "matchRate", "0%");
  }

  /** Clears the loaded data. */
  public synchronized void clear() {
    this.mappings = Collections.emptyList();
    this.urlIndex = new ConcurrentHashMap<>();
    this.mdPathIndex = new ConcurrentHashMap<>();
    this.fileNameIndex = new ConcurrentHashMap<>();
    this.loaded = false;
  }

  private void scanAllMdFiles() {
    try {
      String docsBase = System.getProperty("hop.docs.base", "docs/hop-assistant-manual");
      java.nio.file.Path fsPath = java.nio.file.Path.of(docsBase);
      if (java.nio.file.Files.exists(fsPath)) {
        java.nio.file.Files.walk(fsPath)
            .filter(java.nio.file.Files::isRegularFile)
            .filter(p -> p.toString().endsWith(".md"))
            .filter(p -> !p.toString().endsWith("README.md"))
            .forEach(
                p -> {
                  String relativePath = fsPath.relativize(p).toString();
                  addMdFileToIndex(relativePath);
                });
        LOG.info("Scanned {} MD files from filesystem", mdPathIndex.size());
      }
    } catch (Exception e) {
      LOG.warn("Failed to scan MD files", e);
    }
  }

  private void addMdFileToIndex(String relativePath) {
    if (!mdPathIndex.containsKey(relativePath)) {
      UrlMapping mapping = new UrlMapping();
      mapping.setMdRelativePath(relativePath);
      mapping.setStatus("matched");
      mapping.setAnnotationType("Manual");
      mapping.setPluginId(
          "manual-"
              + java.nio.file.Path.of(relativePath).getFileName().toString().replace(".md", ""));
      mapping.setDocumentationUrl(generateUrlFromMdPath(relativePath));
      mdPathIndex.put(relativePath, mapping);
      fileNameIndex.put(java.nio.file.Path.of(relativePath).getFileName().toString(), mapping);
    }
  }

  private String generateUrlFromMdPath(String mdPath) {
    if (mdPath == null) {
      return null;
    }
    String url = mdPath.replace(".md", ".html");
    url =
        url.replace("03-转换插件/", "pipeline/transforms/")
            .replace("04-动作插件/", "workflow/actions/")
            .replace("05-数据库插件/", "database/databases/")
            .replace("06-元数据类型/", "metadata-types/")
            .replace("10-HopGUI/", "hop-gui/");
    url = url.replaceAll("\\d+-", "");
    if (!url.startsWith("/")) {
      url = "/" + url;
    }
    return url;
  }

  /** Reloads the mapping table. */
  public synchronized void reload() {
    clear();
    load();
  }
}
