/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hop.rest.v1.resources.docs;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Service that loads and queries the URL-to-documentation mapping table. The mapping table is
 * generated by {@code scripts/build-url-mapping.py} and stored as {@code
 * docs/hop-assistant-manual/url-mapping.json}.
 */
public class UrlMappingService {

  private static final Logger LOG = LoggerFactory.getLogger(UrlMappingService.class);
  private static final UrlMappingService INSTANCE = new UrlMappingService();

  private volatile List<UrlMapping> mappings = Collections.emptyList();
  private volatile Map<String, UrlMapping> urlIndex = new ConcurrentHashMap<>();
  private volatile boolean loaded = false;

  public static UrlMappingService getInstance() {
    return INSTANCE;
  }

  private UrlMappingService() {}

  /** Loads the mapping table from the classpath or filesystem. */
  public synchronized void load() {
    if (loaded) {
      return;
    }
    try {
      ObjectMapper mapper = new ObjectMapper();
      InputStream is = loadMappingStream();
      if (is == null) {
        LOG.warn("url-mapping.json not found on classpath or filesystem");
        loaded = true;
        return;
      }
      UrlMappingRoot root = mapper.readValue(is, new TypeReference<UrlMappingRoot>() {});
      this.mappings = root.getMappings() != null ? root.getMappings() : Collections.emptyList();
      this.urlIndex = new ConcurrentHashMap<>();
      for (UrlMapping m : this.mappings) {
        if (m.getDocumentationUrl() != null) {
          urlIndex.put(m.getDocumentationUrl(), m);
        }
      }
      loaded = true;
      Map<String, Object> stats = root.getStats();
      LOG.info(
          "Loaded URL mapping: {} total, {} matched, {} unmatched",
          stats.getOrDefault("total", 0),
          stats.getOrDefault("matched", 0),
          stats.getOrDefault("unmatched", 0));
    } catch (IOException e) {
      LOG.error("Failed to load url-mapping.json", e);
      loaded = true;
    }
  }

  private InputStream loadMappingStream() {
    InputStream is = getClass().getResourceAsStream("/org/apache/hop/rest/docs/url-mapping.json");
    if (is != null) {
      return is;
    }
    is = getClass().getResourceAsStream("/url-mapping.json");
    if (is != null) {
      return is;
    }
    String docsBase = System.getProperty("hop.docs.base", "docs/hop-assistant-manual");
    Path path = Path.of(docsBase, "url-mapping.json");
    if (Files.exists(path)) {
      try {
        return Files.newInputStream(path);
      } catch (IOException e) {
        LOG.warn("Failed to read mapping from filesystem: {}", path, e);
      }
    }
    return null;
  }

  /**
   * Looks up a documentation URL in the mapping table.
   *
   * @param docUrl the documentation URL path (e.g., "/pipeline/transforms/csvinput.html")
   * @return the mapping entry, or null if not found
   */
  public UrlMapping lookup(String docUrl) {
    load();
    if (docUrl == null || docUrl.isBlank()) {
      return null;
    }
    String normalized = docUrl.startsWith("/") ? docUrl : "/" + docUrl;
    return urlIndex.get(normalized);
  }

  /** Returns all mappings. */
  public List<UrlMapping> getAllMappings() {
    load();
    return mappings;
  }

  /** Returns mapping statistics. */
  public Map<String, Object> getStats() {
    load();
    if (!mappings.isEmpty()) {
      long matched = mappings.stream().filter(m -> "matched".equals(m.getStatus())).count();
      long unmatched = mappings.size() - matched;
      return Map.of(
          "total",
          (long) mappings.size(),
          "matched",
          matched,
          "unmatched",
          unmatched,
          "matchRate",
          String.format("%.1f%%", matched * 100.0 / mappings.size()));
    }
    return Map.of("total", 0, "matched", 0, "unmatched", 0, "matchRate", "0%");
  }

  /** Clears the loaded data. */
  public synchronized void clear() {
    this.mappings = Collections.emptyList();
    this.urlIndex = new ConcurrentHashMap<>();
    this.loaded = false;
  }

  /** Reloads the mapping table. */
  public synchronized void reload() {
    clear();
    load();
  }
}
